# Used as base example: https://github.com/CircleCI-Public/circleci-demo-javascript-express/blob/master/.circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.16.0-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          # Run local steps before AWS is required so if they
          # fail you don't waste build time installing AWS CLI

          # Install AWS CLI
          # - include aws cli ci docker:
          #     https://github.com/circleci/circleci-images/issues/53
          # - use global install for aws and pip instead of --user:
          #     https://discuss.circleci.com/t/how-to-add-a-path-to-path-in-circle-2-0/11554
          name: Install awscli
          command: |
            sudo apt-get update && sudo apt-get install -qq -y awscli
      # cache based on our lock file
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
          - ./node_modules
      # running unit tests2
      - run:
          name: Run unit tests
          command: npm run lint && npm run test
      # building
      - run:
          name: Build and Prerender
          command: npm run build && npm run prerender
      - deploy:
          name: Deploy to s3 and cloudfront invalidation
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Depolyment for production"
              ./.circleci/production.sh
            elif [[ ${CIRCLE_BRANCH} =~ int\/.* ]]; then
              echo "No depolyment for staging"
              # ./.circleci/staging.sh
            elif [[ ${CIRCLE_BRANCH} =~ hot\/.* ]]; then
              echo "No depolyment for hot fixes"
              # ./.circleci/staging.sh
            fi
workflows:
  build:
    jobs:
    - build:
        filters:
          branches:
            only:
              - master
              #- /int\/.*/
              #- /hot\/.*/
